// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD68KBjBsaldAP3qqtPH3k54WCGVwHaFFk',
    appId: '1:802145565370:web:3bb9e67b1c1beb07c82083',
    messagingSenderId: '802145565370',
    projectId: 'todolist-bd28f',
    authDomain: 'todolist-bd28f.firebaseapp.com',
    storageBucket: 'todolist-bd28f.firebasestorage.app',
    measurementId: 'G-WWXDXNSXHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKOki81cOPUd_uNGZ3lXFjw8cOuiS3NU',
    appId: '1:802145565370:android:dd0dd3b1df8d33f0c82083',
    messagingSenderId: '802145565370',
    projectId: 'todolist-bd28f',
    storageBucket: 'todolist-bd28f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEnSclOhKbT_7I7C7HeR6EJJOxltzYChE',
    appId: '1:802145565370:ios:5c29ae5ca6260c1ec82083',
    messagingSenderId: '802145565370',
    projectId: 'todolist-bd28f',
    storageBucket: 'todolist-bd28f.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEnSclOhKbT_7I7C7HeR6EJJOxltzYChE',
    appId: '1:802145565370:ios:5c29ae5ca6260c1ec82083',
    messagingSenderId: '802145565370',
    projectId: 'todolist-bd28f',
    storageBucket: 'todolist-bd28f.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD68KBjBsaldAP3qqtPH3k54WCGVwHaFFk',
    appId: '1:802145565370:web:426732e1b38a2392c82083',
    messagingSenderId: '802145565370',
    projectId: 'todolist-bd28f',
    authDomain: 'todolist-bd28f.firebaseapp.com',
    storageBucket: 'todolist-bd28f.firebasestorage.app',
    measurementId: 'G-ZG9JFMK1YP',
  );

}